# revoke repo dispatch on k8s-deployment to triggle deployment
# k8s-deployment & argocd will handle next steps.
name: DispatchDeploy

on:
  push:
    branches:
      - master
      - staging
      - release
jobs:
  image-build:
    runs-on: ubuntu-latest
    if : ${{ github.event_name=='push' || !contains('master,staging,release',github.head_ref) }}
    steps:
      - uses: actions/checkout@master
      - uses: FranzDiebold/github-env-vars-action@v1.2.1
      - uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: auryc-build-master
          password: ${{ secrets.TOKEN_GITHUB_PACKAGES }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          cache-from: type=registry,ref=ghcr.io/auryc-inc/cache
          cache-to:   type=registry,ref=ghcr.io/auryc-inc/cache
          tags: |
            ghcr.io/${{ github.repository }}:${{env.GITHUB_SHA_SHORT}}
            ghcr.io/${{ github.repository }}:${{env.GITHUB_REF_NAME_SLUG}}

  deploy:
    # deploy new image to development/staging/production
    if: ${{ github.event_name=='push' && contains('master,staging,release',github.ref_name) }}
    # needs: image-build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: FranzDiebold/github-env-vars-action@v1.2.1
    - id: last-commit
      run: |
        echo "::set-output name=author-name::$(git --no-pager log -1 --pretty=format:'%an')"
        echo "::set-output name=author-email::$(git --no-pager log -1 --pretty=format:'%ae')"
        echo "::set-output name=subject::$(git --no-pager log -1 --pretty=format:'%s')"
        echo "::set-output name=hash::$(git --no-pager log -1 --pretty=format:'%h')"

        case ${{github.ref_name}} in
            master)   
              echo "::set-output name=target-env::development"
              echo "::set-output name=emoji::cat"  ;;
            staging)  
              echo "::set-output name=target-env::staging"
              echo "::set-output name=emoji::fox_face"  ;;
            release)  
              echo "::set-output name=target-env::production"
              echo "::set-output name=emoji::tiger"  ;;
        esac
    - name: Deploy
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.TOKEN_GITHUB_REPOS }}
        repository: auryc-inc/k8s-deployment
        event-type: deploy
        client-payload: >
          {
            "env": "${{steps.last-commit.outputs.target-env}}",
            "app": "${{env.GITHUB_REPOSITORY_NAME}}",
            "tag": "${{env.GITHUB_SHA_SHORT}}",
            "message": ":${{steps.last-commit.outputs.emoji}}:  auryc-inc/${{env.GITHUB_REPOSITORY_NAME}}@${{steps.last-commit.outputs.hash}} ${{steps.last-commit.outputs.subject}}",
            "user": {
              "name": "${{ steps.last-commit.outputs.author-name }}",
              "email": "${{ steps.last-commit.outputs.author-email }}"
            }
          }