# revoke repo dispatch on k8s-deployment to triggle deployment
# k8s-deployment & argocd will handle next steps.
name: DispatchDeploy

on:
  push:
    branches:
      - master
      - release
jobs:
  dev-app:
    if: ${{github.ref == 'refs/heads/master'}}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: FranzDiebold/github-env-vars-action@v1.2.1
    - id: last-commit
      run: |
        echo "::set-output name=author-name::$(git --no-pager log -1 --pretty=format:'%an')"
        echo "::set-output name=author-email::$(git --no-pager log -1 --pretty=format:'%ae')"
        echo "::set-output name=subject::$(git --no-pager log -1 --pretty=format:'%s')"
        echo "::set-output name=hash::$(git --no-pager log -1 --pretty=format:'%h')"
    - name: Deploy
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.TOKEN_GITHUB_REPOS }}
        repository: auryc-inc/k8s-deployment
        event-type: deploy
        client-payload: >
          {
            "env": "development",
            "app": "${{env.GITHUB_REPOSITORY_NAME}}",
            "tag": "${{env.GITHUB_SHA_SHORT}}",
            "message": ":package:  auryc-inc/${{env.GITHUB_REPOSITORY_NAME}}@${{steps.last-commit.outputs.hash}} ${{steps.last-commit.outputs.subject}}",
            "user": {
              "name": "${{ steps.last-commit.outputs.author-name }}",
              "email": "${{ steps.last-commit.outputs.author-email }}"
            }
          }