
name: PR

on:
  push:
    branches:
      - master
      - staging
      
jobs:

  Draft-Staging-PR:
    if: ${{github.ref == 'refs/heads/master'}}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0
    - name: draft production relase
      run:
        echo ${{ secrets.TOKEN_GITHUB_REPOS }} | gh auth login --with-token && 
        gh pr create -f -B staging -H master -t "Make Release Candidate (master->staging)" || true

  Draft-Production-PR:
    if: ${{github.ref == 'refs/heads/staging'}}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0
    - name: draft production relase
      run:
        echo ${{ secrets.TOKEN_GITHUB_REPOS }} | gh auth login --with-token && 
        gh pr create -f -B release -H staging -t "Make Production Release (staging->release)" || true
